### ISSUE TITLE
[FEAT] 애러 처리

### ISSUE THREAD

**Issue by evryhungry** [Club-PARD/Rainbow_BE#46]
## Issue
- 모든 controller 애러 처리

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [ ] post error handling
- [ ] user error handling
- [ ] picture error handling
- [ ] question error handling

**Comment by evryhungry** [comment]
Global 예외 처리 함수도 생성 및 적용
