### ISSUE TITLE
[FEAT] Error Handling

### ISSUE THREAD

**Issue by evryhungry** [Club-PARD/Rainbow_BE#48]
## Issue

- 예외 처리 만들어서 웹에 보내기

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [x] Post Error Handling
- [x] Community Error Handling

**Comment by evryhungry** [comment]
## To-do
- [x] User Error Handling
